### ISSUE TITLE
Make an NPM module

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-js#1]

**Comment by scottkellum** [comment]
https://github.com/yurivictor/typebetter/pull/10

**Comment by scottkellum** [comment]
https://www.npmjs.com/package/modularscale-js

**Comment by KyleAMathews** [comment]
BTW, adding a [UMD](https://github.com/umdjs/umd) header to the file would help make this module more consumable. Many JS apps now expect to be able to require frontend code using requires e.g. `var ms = require('modularscale-js')`

**Comment by scottkellum** [comment]
@KyleAMathews Thanks! I will read up and try to implement.

**Comment by rafegoldberg** [comment]
agree with @KyleAMathews re: adding UMD compatibility for `var ms= require('modular-scale')`

**Comment by scottkellum** [comment]
Could one of y’all PR this UMD thing? It’d help me a lot

**Comment by KyleAMathews** [comment]
Eh commonjs won so UMD isn't really necessary anymore. Just add a `module.exports = ms` at the end and you're good.

**Comment by scottkellum** [comment]
@KyleAMathews Thanks, apologies for my ignorance but where do I add this?

**Comment by KyleAMathews** [comment]
At the bottom of modularscale.js

**Comment by scottkellum** [comment]
ah, ok thanks
