### ISSUE TITLE
Filter unique base

### ISSUE THREAD

**Issue by iksi** [modularscale/modularscale-js#4]
I’ve been experimenting a bit with version 3.0 and when I use the following input values the same output gets returned for different scale numbers:

```
var settings = {
  base: [1, 2.25],
  ratio: 1.5,
}
```

Scale it produces:

```
16: 25.62890625
15: 17.0859375
14: 17.0859375
13: 11.390625
12: 11.390625
11: 7.59375
10: 7.59375
9: 5.0625
8: 5.0625
7: 3.375
6: 3.375
5: 2.25
4: 2.25
3: 1.5
2: 1.5
1: 1
0: 1
-1: 0.66666666666667
-2: 0.66666666666667
-3: 0.44444444444444
-4: 0.44444444444444
-5: 0.2962962962963
-6: 0.2962962962963
```

I think the normalized base variable should be filtered on unique values so the following scale would be returned:

```
16: 656.84083557129
15: 437.89389038086
14: 291.92926025391
13: 194.61950683594
12: 129.74633789062
11: 86.49755859375
10: 57.6650390625
9: 38.443359375
8: 25.62890625
7: 17.0859375
6: 11.390625
5: 7.59375
4: 5.0625
3: 3.375
2: 2.25
1: 1.5
0: 1
-1: 0.66666666666667
-2: 0.44444444444444
-3: 0.2962962962963
-4: 0.19753086419753
-5: 0.13168724279835
-6: 0.087791495198903
```

**Comment by scottkellum** [comment]
Thanks @iksi, I’ll think about this. I’m a bit conflicted as to this behavior, on one hand I want people to see when their bases are reduced down to the same thing and removing them gives no indication that the bases are identical. Also programatic applications of modular scale might result in unintended behavior if non unique values are truncated.

However I see your point and it’s how 2.0 worked. I’ll think about it.

**Comment by iksi** [comment]
Thanks @scottkellum, I mainly wanted to point out the behaviour as I couldn’t figure out if it was intentional or not.
